config/routes.rb
Rails.application.routes.draw do
  resources :payment_sources
  resources :chats
  resources :messages

  resources :offers do
    member do
      get :accept
    end
  end
  
  resources :help_requests do
    member do
      get :finish, :accept
    end
  end



  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get '/home' => 'application#home'
  get '/account' => 'application#account'
  get '/current_request' => 'application#current_request'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    root to: "application#home"
  end

  root to: "application#landing"
end

app/models/payment_source.rb
class PaymentSource < ApplicationRecord
end

app/controllers/payment_sources_controller.rb
class PaymentSourcesController < ApplicationController
  before_action :set_payment_source, only: [:show, :edit, :update, :destroy]

  # GET /payment_sources
  # GET /payment_sources.json
  def index
    @payment_sources = PaymentSource.all
  end

  # GET /payment_sources/1
  # GET /payment_sources/1.json
  def show
  end

  # GET /payment_sources/new
  def new
    @payment_source = PaymentSource.new
  end

  # GET /payment_sources/1/edit
  def edit
  end

  # POST /payment_sources
  # POST /payment_sources.json
  def create
    @payment_source = PaymentSource.new(payment_source_params)

    respond_to do |format|
      if @payment_source.save
        format.html { redirect_to @payment_source, notice: 'Payment source was successfully created.' }
        format.json { render :show, status: :created, location: @payment_source }
      else
        format.html { render :new }
        format.json { render json: @payment_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_sources/1
  # PATCH/PUT /payment_sources/1.json
  def update
    respond_to do |format|
      if @payment_source.update(payment_source_params)
        format.html { redirect_to @payment_source, notice: 'Payment source was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_source }
      else
        format.html { render :edit }
        format.json { render json: @payment_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_sources/1
  # DELETE /payment_sources/1.json
  def destroy
    @payment_source.destroy
    respond_to do |format|
      format.html { redirect_to payment_sources_url, notice: 'Payment source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_source
      @payment_source = PaymentSource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_source_params
      params.require(:payment_source).permit(:last_4, :cvc, :exp_year, :exp_month, :student_id)
    end
end

app/helpers/payment_sources_helper.rb
module PaymentSourcesHelper
end

app/views/payment_sources/_form.html.erb
<%= form_with(model: payment_source, local: true) do |form| %>
  <% if payment_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment_source.errors.count, "error") %> prohibited this payment_source from being saved:</h2>

      <ul>
      <% payment_source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :last_4 %>
    <%= form.text_field :last_4 %>
  </div>

  <div class="field">
    <%= form.label :cvc %>
    <%= form.text_field :cvc %>
  </div>

  <div class="field">
    <%= form.label :exp_year %>
    <%= form.text_field :exp_year %>
  </div>

  <div class="field">
    <%= form.label :exp_month %>
    <%= form.text_field :exp_month %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.number_field :student_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payment_sources/edit.html.erb
<h1>Editing Payment Source</h1>

<%= render 'form', payment_source: @payment_source %>

<%= link_to 'Show', @payment_source %> |
<%= link_to 'Back', payment_sources_path %>

app/views/payment_sources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payment Sources</h1>

<table>
  <thead>
    <tr>
      <th>Last 4</th>
      <th>Cvc</th>
      <th>Exp year</th>
      <th>Exp month</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_sources.each do |payment_source| %>
      <tr>
        <td><%= payment_source.last_4 %></td>
        <td><%= payment_source.cvc %></td>
        <td><%= payment_source.exp_year %></td>
        <td><%= payment_source.exp_month %></td>
        <td><%= payment_source.student_id %></td>
        <td><%= link_to 'Show', payment_source %></td>
        <td><%= link_to 'Edit', edit_payment_source_path(payment_source) %></td>
        <td><%= link_to 'Destroy', payment_source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment Source', new_payment_source_path %>

app/views/payment_sources/new.html.erb
<script src="https://js.stripe.com/v3/"></script>

<form action="/charge" method="post" id="payment-form">
  <div class="form-row">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button>Submit Payment</button>
</form>

app/views/payment_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last 4:</strong>
  <%= @payment_source.last_4 %>
</p>

<p>
  <strong>Cvc:</strong>
  <%= @payment_source.cvc %>
</p>

<p>
  <strong>Exp year:</strong>
  <%= @payment_source.exp_year %>
</p>

<p>
  <strong>Exp month:</strong>
  <%= @payment_source.exp_month %>
</p>

<p>
  <strong>Student:</strong>
  <%= @payment_source.student_id %>
</p>

<%= link_to 'Edit', edit_payment_source_path(@payment_source) %> |
<%= link_to 'Back', payment_sources_path %>