config/routes.rb
Rails.application.routes.draw do
  resources :payment_sources
  resources :chats
  resources :messages

  resources :offers do
    member do
      get :accept
    end
  end
  
  resources :help_requests do
    member do
      get :finish, :accept
    end
  end



  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get '/home' => 'application#home'
  get '/account' => 'application#account'
  get '/current_request' => 'application#current_request'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    root to: "application#home"
  end

  root to: "application#landing"
end

app/models/help_request.rb
class HelpRequest < ApplicationRecord
  has_one_attached :problem_picture
  belongs_to :subject
  belongs_to :student
  belongs_to :tutor, optional: true
  enum state: [:pending, :in_progress, :finished]
  has_many :offers

  def in_progress?
    state == 'in_progress' 
  end
end

app/controllers/help_requests_controller.rb
class HelpRequestsController < ApplicationController
  before_action :check_if_student!, only: [:destroy, :edit, :update, :create, :new]
  before_action :set_help_request, only: [:edit, :update, :destroy, :finish]


  # GET /help_requests
  # GET /help_requests.json
  def index
    @help_requests = current_user.help_requests.all
  end

  # GET /help_requests/1
  # GET /help_requests/1.json
  def show
    if current_user.tutor?
      @help_request = HelpRequest.find(params[:id])
    else
      @help_request = current_user.help_requests.find(params[:id])
      @offers = @help_request.offers
    end
  end

  def accept
    @help_request = HelpRequest.find(params[:id])
    if @help_request.state == "pending"
      @help_request.update(tutor_id: current_user.id, state: 1)
      @help_request.offers.update_all(state: 2)
      redirect_to chat_for_redirect
    else
      redirect_to @help_request
    end
  end

  def finish
    if current_user.student?
      @help_request.update(state: 2) if @help_request.state == "in_progress"
      redirect_to current_request_path
    else
      redirect_to @root_path
     end
  end

  # GET /help_requests/new
  def new
    @help_request = current_user.help_requests.new
  end

  # GET /help_requests/1/edit
  def edit
  end

  # POST /help_requests
  # POST /help_requests.json
  def create
    @help_request = current_user.help_requests.new(help_request_params)

    respond_to do |format|
      if @help_request.save
        format.html { redirect_to current_request_path, notice: 'Help request was successfully created.' }
        format.json { render :show, status: :created, location: @help_request }
      else
        format.html { render :new }
        format.json { render json: @help_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /help_requests/1
  # PATCH/PUT /help_requests/1.json
  def update
    respond_to do |format|
      if @help_request.update(help_request_params)
        format.html { redirect_to @help_request, notice: 'Help request was successfully updated.' }
        format.json { render :show, status: :ok, location: @help_request }
      else
        format.html { render :edit }
        format.json { render json: @help_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /help_requests/1
  # DELETE /help_requests/1.json
  def destroy
    @help_request.destroy
    respond_to do |format|
      format.html { redirect_to help_requests_url, notice: 'Help request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def chat_for_redirect
      Chat.where(chat_params).first || Chat.create(chat_params)
    end

    def chat_params
      {
        student_id: @help_request.student_id,
        tutor_id: current_user.id
      }
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_help_request
      @help_request = current_user.help_requests.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def help_request_params
      params.require(:help_request).permit(:description, :subject_id, :price, :problem_picture)
    end

    def check_if_student!
      redirect_to root_path unless current_user.student?
    end

end

app/helpers/help_requests_helper.rb
module HelpRequestsHelper
  def problem_picture_default(help_request)
    problem = help_request.problem_picture
    return url_for(problem) if problem.attached?
    asset_pack_path "media/images/avatar.svg"
  end
end

app/views/help_requests/_form.html.erb
<%= form_with(model: help_request, local: true) do |form| %>
  <% if help_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(help_request.errors.count, "error") %>
        prohibited this help_request from being saved:
      </h2>
      <ul>
        <% help_request.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id="payment_form_first_block">
    <div class="help_request_data">
      <div class="help_request_photo">
        <p class="photo_title">Add a Screenshot Your Problem</p>
        <p class="photo_title--with_padding">(Optional)</p>
        <div id="photo_file" class="photo_file">
          <div class="photo_file_picture" id="photo_file_picture"></div>
          <%= form.file_field :problem_picture, class:'photo_input', accept:"image/*"%>
        </div>
        <img id="output"/>
      </div>
      <div class="help_request_inputs">
        <div class="help_request_form_field">
          <%= form.label :subject_id, class:"field_title"%>
          <%= form.select :subject_id, options_for_select(Subject.all.pluck(:name, :id), selected: form.object.subject), {},  class: "field_input select" %>
        </div>
        <div class="help_request_form_field">
          <%= form.label :description, class: "field_title"%>
          <%= form.text_area :description, class: "field_input_description field_input", placeholder: "Description"%>
        </div>
        <div class="help_request_form_field">
          <p class="field_title">
            Attach Your Files
          </p>
          <div class="attachment_field_description">
            <button class="attachment_button" disabled="disabled">+</button>
            <div class="attachment_field_content">
              <p class="attachment_field_title">
                Drag files here or browse
              </p>
              <p>
                Supported file types: PDF, DOC, DOCX, JPEG, JPG, TIFF, BMP, XLS and XLSX
              </p>
            </div>
          </div>
        </div>
        <div class="help_request_next_part">
          <button type="button" id="show_payment_section_button" class="common_button">Next</button>
        </div>
      </div>
    </div>
  </div>
  <div id="payment_form_second_block" class="payment_form_second_block hidden_form">
    <%= form.label :price, class:"second_block_title"%>
    <%= form.number_field :price, placeholder:"$", class:"field_input"%>
    <%= form.submit 'Finish Tutor Request', class: 'common_button request_price_button'%>
  </div>
<% end %>

app/views/help_requests/_help_requests_list.html.erb
<table class="list" cellspaceing="0">
  <thead class="head_list">
    <tr>
      <th class="column">Subject</th>
      <th class="column">Problem</th>
      <th class="column">Date</th>
      <th class="column">Price</th>
      <th class="column">State</th>
    </tr>
  </thead>
  <% @help_requests.each do |help_request| %>
    <tr class="row">
      <td class="column first"><%= help_request.subject.name %></td>
      <td class="column">
        <%= link_to help_request.description, help_request_path(help_request) %>
      </td>
      <td class="column"><%= help_request.created_at.strftime("%d %b, %Y") %></td>
      <td class="column last"><span>$<%= help_request.price %></span></td>
      <td class="column offer_state <%= red_if_request_finished(help_request.state) %>">
        <%= help_request.state.capitalize.tr('_', ' ') %>
      </td>
    </tr>
  <% end %>
</table>

app/views/help_requests/edit.html.erb
<h1>Editing Help Request</h1>

<%= render 'form', help_request: @help_request %>

<%= link_to 'Show', @help_request %> |
<%= link_to 'Back', help_requests_path %>

app/views/help_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="request_headline">All Requests</h1>
<%= render 'help_requests_list' %>

app/views/help_requests/new.html.erb
<section class="headlines"> 
  <h1>Request Tutor</h1> 
</section>

<%= render 'form', help_request: @help_request %>

app/views/help_requests/show.html.erb
<div class="show_request">

  <section class="request_headline_img">
    <%= link_to current_request_path do %>
      <%= image_tag asset_pack_path 'media/images/arrow_left.svg', class: "arrow_left" %>
    <% end %>
    <section class="headlines headlines--for_help">
      <h1>Very Urgent,Help!!! <%= @help_request.subject.name %> </h1>
    </section>
  </section>

  <section class="container_user">
    <div class="avatar_user"></div>
    <div class="user_info">
      <p>User:
        <%= @help_request.student.first_name %>
        <%= @help_request.student.last_name %>
      </p>
      <span><%= @help_request.created_at.strftime("%d %B, %Y") %></span>
    </div>
  </section>

  <section class="help_request_data">
    <div class="help_request_photo">
      <p class="photo_title">A Screenshot of the Problem</p>
      <div class="photo_file">
        <div class="photo_file_picture" style="background-image: url(<%= problem_picture_default(@help_request) %>)"></div>
      </div>
    </div>
    <div class="help_request_inputs">
      <div class="help_request_form_field form_field">
        <p class="field_title">
          Subject:
        </p>
        <input value="<%= @help_request.subject.name %>" type="text" class="field_input" readonly>
      </div>
      <div class="help_request_form_field form_field">
        <p class="field_title">
          The Problems:
        </p>
        <textarea disabled class="field_input field_input_description"><%= @help_request.description %></textarea>
      </div>
      <div class="price">
        <p>
          Current Price:
          <span><%= @help_request.price %></span>
        </p>
      </div>
    </div>
  </section>
  <% if current_user.student? && @help_request.state == "in_progress" %>
    <%= link_to 'Finish', finish_help_request_path(@help_request), class: "common_button" %>
  <% end %>

  <% if current_user.tutor? && @help_request.state == "pending" %>
    <section class="help_request_next_part actions">
      <% unless current_user.offers.map{|o| o.help_request_id}.include?(@help_request.id) %>
        <%= link_to 'New Offer', new_offer_path(help_request_id:@help_request.id), class: "common_button" %>
      <% end %>
      <%= link_to 'Help Now!', accept_help_request_path(@help_request), class: "common_button" %>
    </section>
  <% end %>

  <% if current_user.student? && @help_request.state == "pending" %>
    <% if @offers.any? %>
      <table class="list" cellspaceing="0">
        <thead class="head_list">
          <tr>
            <th class="column">Name</th>
            <th class="column">Email</th>
            <th class="column">New Price</th>
            <th class="column">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @offers.each do |offer| %>
            <tr class="row">
              <td class="column"><%= offer.tutor.first_name %> <%= offer.tutor.last_name %></td>
              <td class="column"><%= offer.tutor.email %></td>
              <td class="column">$<%= offer.new_price %></td>
              <td class="column"><%= link_to 'Accept', accept_offer_path(offer), class: "accept_tutor_button", remote: true  %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
    <section class="headlines headlines--without_offers">
      <h1>You have no offers</h1>
    </section>
    <% end %>
  <% end %>
</div>
<div id="modal_placeholder"></div>