config/routes.rb
Rails.application.routes.draw do
  resources :payment_sources
  resources :chats
  resources :messages

  resources :offers do
    member do
      get :accept
    end
  end
  
  resources :help_requests do
    member do
      get :finish, :accept
    end
  end



  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get '/home' => 'application#home'
  get '/account' => 'application#account'
  get '/current_request' => 'application#current_request'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    root to: "application#home"
  end

  root to: "application#landing"
end

app/views/layouts/_navbar.html.erb
<div class="logo">
  <%= link_to root_path do %>
    <img src="<%= asset_pack_path 'media/images/tutoru.svg' %>" alt="logo">
  <% end %>
</div>
<nav>
  <ul>
    <li>
      <%= link_to "Home", home_path, class: "#{controller_name == 'application' && action_name == 'home' ? 'active' : ''}" %>
    </li>
    <li>
      <%= link_to "Current Requests", current_request_path, class: "#{(controller_name == 'application' && action_name == 'current_request') || (controller_name == 'help_requests' && action_name == 'new') ? 'active' : ''}" %>
    </li>
    <% if current_user %>
      <li>
        <%= link_to "Chats", chats_path(id: current_user.id), class: "#{(controller_name == 'chats') ? 'active' : ''}" %>
      </li>
      <li>
        <%= link_to "Account", account_path(id: current_user.id), class: "#{(controller_name == 'application' && action_name == 'account') ? 'active' : ''}" %>
      </li>
    <% end %>
    <li>
      <a href="#">Settings</a>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutoru</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <%= render "layouts/navbar" %>
    </header>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>